swagger: "2.0"
info:
  description: "This is the API of the Istio BookInfo sample application."
  version: "1.0.0"
  title: "BookInfo Ratings"
  termsOfService: "https://istio.io/"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/api/v1"
tags:
- name: "ratings"
externalDocs:
  description: "Learn more about the Istio BookInfo application"
  url: "https://istio.io/docs/samples/bookinfo.html"
paths:
  /ratings/{id}:
    get:
      tags:
      - "ratings"
      summary: "Get ratings for a product"
      description: "Get ratings for a product, including stars and their color."
      operationId: "getProductRatings"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Product id"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ProductRatings"
        400:
          description: "Invalid product id"
        500:
          description: "No connection to ratings database"

definitions:
  ProductRatings:
    type: "object"
    description: "Object containing ratings of a product"
    properties:
      id:
        type: "integer"
        format: "int32"
        description: "Product id"
      ratings:
        type: "object"
        description: "A hashmap where keys are reviewer names, values are number of stars"
        additionalProperties: 
          type: "string"
    required:
    - "id"
    - "ratings"