swagger: "2.0"
info:
  description: "This is the API of the Istio BookInfo sample application."
  version: "1.0.0"
  title: "BookInfo Reviews"
  termsOfService: "https://istio.io/"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/api/v1"
tags:
- name: "reviews"
externalDocs:
  description: "Learn more about the Istio BookInfo application"
  url: "https://istio.io/docs/samples/bookinfo.html"
paths:
  /reviews/{id}:
    get:
      tags:
      - "reviews"
      summary: "Get reviews for a product"
      description: "Get reviews for a product, including review text and possibly ratings information."
      operationId: "getProductReviews"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Product id"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ProductReviews"
        400:
          description: "Invalid product id"
  
definitions:
  ProductReviews:
    type: "object"
    description: "Object containing reviews for a product"
    properties:
      id:
        type: "integer"
        format: "int32"
        description: "Product id"
      reviews:
        type: "array"
        description: "List of reviews"
        items:
          $ref: "#/definitions/Review"
    required:
    - "id"
    - "reviews"
  Review:
    type: "object"
    description: "Review of a product"
    properties:
      reviewer:
        type: "string"
        description: "Name of the reviewer"
      text:
        type: "string"
        description: "Review text"
      rating:
        $ref: "#/definitions/Rating"
    required:
    - "reviewer"
    - "text"
  Rating:
    type: "object"
    description: "Rating of a product"
    properties:
      stars:
        type: "integer"
        format: "int32"
        minimum: 1
        maximum: 5
        description: "Number of stars"
      color:
        type: "string"
        enum:
          - "red"
          - "black"
        description: "Color in which stars should be displayed"
    required:
    - "stars"
    - "color"